package main.java.Quality;

import main.java.Base.GClazz;
import main.java.DT.GLog;
import main.java.Sys.GStatic;

/**
 * 质量算法
 */
public class GQualityAlgo {
	
    /**
     *  构造函数
     */
	public GQualityAlgo(){
		GClazz.thisADataUnitClass();
	}
	
	/**
	 * 功能性
	 * 在指定条件下,软件满足用户显式需求和隐式需求的能力
	 * 1.默认算法：以下各项满分均为20分
	 * 2.条件算法：按照不同的
	 */
	private Integer FUNCTIONALITY = 0;
	public Integer getFUNCTIONALITY() {
		return FUNCTIONALITY;
	}
	public void setFUNCTIONALITY(Integer fUNCTIONALITY) {
		FUNCTIONALITY = fUNCTIONALITY;
	}
	
	/**
	 * 适应性
	 */
	private Integer FUNCTIONALITY_FLEXIBILITY = 0;
	public Integer getFUNCTIONALITY_FLEXIBILITY() {
		return FUNCTIONALITY_FLEXIBILITY;
	}
	public void setFUNCTIONALITY_FLEXIBILITY(Integer fUNCTIONALITY_FLEXIBILITY) { FUNCTIONALITY_FLEXIBILITY = fUNCTIONALITY_FLEXIBILITY; }
	
	/**
	 * 准确性
	 */
	private Integer FUNCTIONALITY_ACCURACY = 0;
	public Integer getFUNCTIONALITY_ACCURACY() {
		return FUNCTIONALITY_ACCURACY;
	}
	public void setFUNCTIONALITY_ACCURACY(Integer fUNCTIONALITY_ACCURACY) { FUNCTIONALITY_ACCURACY = fUNCTIONALITY_ACCURACY; }
	
	/**
	 * 交互性
	 */
	private Integer FUNCTIONALITY_INTERACTIVITY = 0;
	public Integer getFUNCTIONALITY_INTERACTIVITY() {
		return FUNCTIONALITY_INTERACTIVITY;
	}
	public void setFUNCTIONALITY_INTERACTIVITY(Integer fUNCTIONALITY_INTERACTIVITY) { FUNCTIONALITY_INTERACTIVITY = fUNCTIONALITY_INTERACTIVITY; }
	
	/**
	 * 安全性
	 */
	private Integer FUNCTIONALITY_SECURITY = 0;
	public Integer getFUNCTIONALITY_SECURITY() {
		return FUNCTIONALITY_SECURITY;
	}
	public void setFUNCTIONALITY_SECURITY(Integer fUNCTIONALITY_SECURITY) { FUNCTIONALITY_SECURITY = fUNCTIONALITY_SECURITY; }

	/**
	 * 功能合规性
	 */
	private Integer FUNCTIONALITY_REGULATORY = 0;
	public Integer getFUNCTIONALITY_REGULATORY() {
		return FUNCTIONALITY_REGULATORY;
	}
	public void setFUNCTIONALITY_REGULATORY(Integer fUNCTIONALITY_REGULATORY) { FUNCTIONALITY_REGULATORY = fUNCTIONALITY_REGULATORY; }
	
	/**
	 * 可靠性
	 * 在指定条件下使用时,软件产品维持规定的性能级别的能力
	 * 成熟性
	 * 容错性
	 * 易恢复性
	 * 可靠合规性
	 */
	private Integer RELIABILITY = 0;
	public Integer getRELIABILITY() {
		return RELIABILITY;
	}
	public void setRELIABILITY(Integer rELIABILITY) {
		RELIABILITY = rELIABILITY;
	}
	
	/**
	 * 成熟性
	 */
	private Integer RELIABILITY_MATURITY = 0;
	public Integer getRELIABILITY_MATURITY() {
		return RELIABILITY_MATURITY;
	}
	public void setRELIABILITY_MATURITY(Integer rELIABILITY_MATURITY) { RELIABILITY_MATURITY = rELIABILITY_MATURITY; }

	/**
	 * 容错性
	 */
	private Integer RELIABILITY_FAULTTOLERANCE = 0;
	public Integer getRELIABILITY_FAULTTOLERANCE() {
		return RELIABILITY_FAULTTOLERANCE;
	}
	public void setRELIABILITY_FAULTTOLERANCE(Integer rELIABILITY_FAULTTOLERANCE) { RELIABILITY_FAULTTOLERANCE = rELIABILITY_FAULTTOLERANCE; }
	
	/**
	 * 易恢复性
	 */
	private Integer RELIABILITY_RECOVERABILITY = 0;
	public Integer getRELIABILITY_RECOVERABILITY() {
		return RELIABILITY_RECOVERABILITY;
	}
	public void setRELIABILITY_RECOVERABILITY(Integer rELIABILITY_RECOVERABILITY) { RELIABILITY_RECOVERABILITY = rELIABILITY_RECOVERABILITY; }
	
	/**
	 * 可靠合规性
	 */
	private Integer RELIABILITY_REGULATORY = 0;
	public Integer getRELIABILITY_REGULATORY() {
		return RELIABILITY_REGULATORY;
	}
	public void setRELIABILITY_REGULATORY(Integer rELIABILITY_REGULATORY) { RELIABILITY_REGULATORY = rELIABILITY_REGULATORY; }
	
	/**
	 * 可使用性
	 * 在指定条件下,软件产品被使用、理解、学习的能力
	 * 易理解性
	 * 易学习性
	 * 易操作性
	 * 用户粘性
	 * 易用合规性
	 */
	private Integer USABILITY = 0;
	public Integer getUSABILITY() {
		return USABILITY;
	}
	public void setUSABILITY(Integer uSABILITY) {
		USABILITY = uSABILITY;
	}
	
	/**
	 * 易理解性
	 */
	private Integer USABILITY_COMPREHENSIBILITY = 0;
	public Integer getUSABILITY_COMPREHENSIBILITY() {
		return USABILITY_COMPREHENSIBILITY;
	}
	public void setUSABILITY_COMPREHENSIBILITY(Integer uSABILITY_COMPREHENSIBILITY) { USABILITY_COMPREHENSIBILITY = uSABILITY_COMPREHENSIBILITY; }
	
	/**
	 * 易学习性
	 */
	private Integer USABILITY_EASYTOLEARN = 0;
	public Integer getUSABILITY_EASYTOLEARN() {
		return USABILITY_EASYTOLEARN;
	}
	public void setUSABILITY_EASYTOLEARN(Integer uSABILITY_EASYTOLEARN) { USABILITY_EASYTOLEARN = uSABILITY_EASYTOLEARN; }
	
	/**
	 * 易操作性
	 */
	private Integer USABILITY_OPERABILITY = 0;
	public Integer getUSABILITY_OPERABILITY() {
		return USABILITY_OPERABILITY;
	}
	public void setUSABILITY_OPERABILITY(Integer uSABILITY_OPERABILITY) { USABILITY_OPERABILITY = uSABILITY_OPERABILITY; }
	
	/**
	 * 用户粘性
	 */
	private Integer USABILITY_STICKINESS = 0;
	public Integer getUSABILITY_STICKINESS() {
		return USABILITY_STICKINESS;
	}
	public void setUSABILITY_STICKINESS(Integer uSABILITY_STICKINESS) { USABILITY_STICKINESS = uSABILITY_STICKINESS; }
	
	/**
	 * 易用合规性
	 */
	private Integer USABILITY_REGULATORY = 0;
	public Integer getUSABILITY_REGULATORY() {
		return USABILITY_REGULATORY;
	}
	public void setUSABILITY_REGULATORY(Integer uSABILITY_REGULATORY) { USABILITY_REGULATORY = uSABILITY_REGULATORY; }
	
	/**
	 * 效率
	 * 在指定条件下,相对于所有资源的数量,软件产品可提供适当性能的能力
	 * 时间特性
	 * 资源利用率
	 * 效率合规性
	 */
	private Integer EFFICIENCY = 0;
	public Integer getEFFICIENCY() {
		return EFFICIENCY;
	}
	public void setEFFICIENCY(Integer eFFICIENCY) {
		EFFICIENCY = eFFICIENCY;
	}
	
	/**
	 * 时间特性
	 */
	private Integer EFFICIENCY_TIMING = 0;
	public Integer getEFFICIENCY_TIMING() {
		return EFFICIENCY_TIMING;
	}
	public void setEFFICIENCY_TIMING(Integer eFFICIENCY_TIMING) {
		EFFICIENCY_TIMING = eFFICIENCY_TIMING;
	}
	
	/**
	 * 资源利用率
	 */
	private Integer EFFICIENCY_UTILIZATION = 0;
	public Integer getEFFICIENCY_UTILIZATION() {
		return EFFICIENCY_UTILIZATION;
	}
	public void setEFFICIENCY_UTILIZATION(Integer eFFICIENCY_UTILIZATION) { EFFICIENCY_UTILIZATION = eFFICIENCY_UTILIZATION; }

	/**
	 * 效率合规性
	 */
	private Integer EFFICIENCY_REGULATORY = 0;
	public Integer getEFFICIENCY_REGULATORY() {
		return EFFICIENCY_REGULATORY;
	}
	public void setEFFICIENCY_REGULATORY(Integer eFFICIENCY_REGULATORY) { EFFICIENCY_REGULATORY = eFFICIENCY_REGULATORY; }
	
	/**
	 * 可维护性
	 * 指软件产品被修改的能力.修改包括修正、优化和功能规格变更的说明
	 * 易分析性
	 * 稳定性
	 * 易变更性
	 * 易测试性
	 * 可维护合规性
	 */
	private Integer MAINTAINABILITY = 0;
	public Integer getMAINTAINABILITY() {
		return MAINTAINABILITY;
	}
	public void setMAINTAINABILITY(Integer mAINTAINABILITY) {
		MAINTAINABILITY = mAINTAINABILITY;
	}
	
	/**
	 * 易分析性
	 */
	private Integer MAINTAINABILITY_ANALYZABILITY = 0;
	public Integer getMAINTAINABILITY_ANALYZABILITY() {
		return MAINTAINABILITY_ANALYZABILITY;
	}
	public void setMAINTAINABILITY_ANALYZABILITY(Integer mAINTAINABILITY_ANALYZABILITY) { MAINTAINABILITY_ANALYZABILITY = mAINTAINABILITY_ANALYZABILITY; }
	
	/**
	 * 稳定性
	 */
	private Integer MAINTAINABILITY_STABILITY = 0;
	public Integer getMAINTAINABILITY_STABILITY() {
		return MAINTAINABILITY_STABILITY;
	}
	public void setMAINTAINABILITY_STABILITY(Integer mAINTAINABILITY_STABILITY) { MAINTAINABILITY_STABILITY = mAINTAINABILITY_STABILITY; }
	
	/**
	 * 易变更性
	 */
	private Integer MAINTAINABILITY_CHANGEABILITY = 0;
	public Integer getMAINTAINABILITY_CHANGEABILITY() {
		return MAINTAINABILITY_CHANGEABILITY;
	}
	public void setMAINTAINABILITY_CHANGEABILITY(Integer mAINTAINABILITY_CHANGEABILITY) { MAINTAINABILITY_CHANGEABILITY = mAINTAINABILITY_CHANGEABILITY; }
	
	/**
	 * 易测试性
	 */
	private Integer MAINTAINABILITY_TESTABILITY = 0;
	public Integer getMAINTAINABILITY_TESTABILITY() {
		return MAINTAINABILITY_TESTABILITY;
	}
	public void setMAINTAINABILITY_TESTABILITY(Integer mAINTAINABILITY_TESTABILITY) { MAINTAINABILITY_TESTABILITY = mAINTAINABILITY_TESTABILITY; }
	
	/**
	 * 可维护合规性
	 */
	private Integer MAINTAINABILITY_REGULATORY = 0;
	public Integer getMAINTAINABILITY_REGULATORY() {
		return MAINTAINABILITY_REGULATORY;
	}
	public void setMAINTAINABILITY_REGULATORY(Integer mAINTAINABILITY_REGULATORY) { MAINTAINABILITY_REGULATORY = mAINTAINABILITY_REGULATORY; }
	
	/**
	 * 可移植性
	 * 指软件产品从一个环境迁移到另一个环境的能力
	 * 适应性
	 * 易安装性
	 * 共存性
	 * 易替换性
	 * 可移植合规性
	 */
	private Integer PORTABILITY = 0;
	public Integer getPORTABILITY() {
		return PORTABILITY;
	}
	public void setPORTABILITY(Integer pORTABILITY) {
		PORTABILITY = pORTABILITY;
	}

	/**
	 * 适应性
	 */
	private Integer PORTABILITY_ADAPTABILITY = 0;
	public Integer getPORTABILITY_ADAPTABILITY() {
		return PORTABILITY_ADAPTABILITY;
	}
	public void setPORTABILITY_ADAPTABILITY(Integer pORTABILITY_ADAPTABILITY) { PORTABILITY_ADAPTABILITY = pORTABILITY_ADAPTABILITY; }

	/**
	 * 易安装性
	 */
	private Integer PORTABILITY_INSTALLATION = 0;
	public Integer getPORTABILITY_INSTALLATION() {
		return PORTABILITY_INSTALLATION;
	}
	public void setPORTABILITY_INSTALLATION(Integer pORTABILITY_INSTALLATION) { PORTABILITY_INSTALLATION = pORTABILITY_INSTALLATION; }
	
	/**
	 * 共存性
	 */
	private Integer PORTABILITY_COEXISTENCE = 0;
	public Integer getPORTABILITY_COEXISTENCE() {
		return PORTABILITY_COEXISTENCE;
	}
	public void setPORTABILITY_COEXISTENCE(Integer pORTABILITY_COEXISTENCE) { PORTABILITY_COEXISTENCE = pORTABILITY_COEXISTENCE; }
	
	/**
	 * 易替换性
	 */
	private Integer PORTABILITY_REPLACEABILITY = 0;
	public Integer getPORTABILITY_REPLACEABILITY() {
		return PORTABILITY_REPLACEABILITY;
	}
	public void setPORTABILITY_REPLACEABILITY(Integer pORTABILITY_REPLACEABILITY) { PORTABILITY_REPLACEABILITY = pORTABILITY_REPLACEABILITY; }
	
	/**
	 * 可移植合规性
	 */
	private Integer PORTABILITY_REGULATORY = 0;
	public Integer getPORTABILITY_REGULATORY() {
		return PORTABILITY_REGULATORY;
	}
	public void setPORTABILITY_REGULATORY(Integer pORTABILITY_REGULATORY) { PORTABILITY_REGULATORY = pORTABILITY_REGULATORY; }
	
	/**
	 * 默认品质算法
	 * 相关各项分数直接相加
	 */
	protected void calculateDefault() {
		FUNCTIONALITY = FUNCTIONALITY_FLEXIBILITY
				+ FUNCTIONALITY_ACCURACY
				+ FUNCTIONALITY_INTERACTIVITY
				+ FUNCTIONALITY_SECURITY
				+ FUNCTIONALITY_REGULATORY;

		RELIABILITY = RELIABILITY_MATURITY
				+ RELIABILITY_FAULTTOLERANCE
				+ RELIABILITY_RECOVERABILITY
				+ RELIABILITY_REGULATORY;
		
		USABILITY = USABILITY_COMPREHENSIBILITY
				+ USABILITY_EASYTOLEARN
				+ USABILITY_OPERABILITY
				+ USABILITY_STICKINESS
				+ USABILITY_REGULATORY;
		
		EFFICIENCY = EFFICIENCY_TIMING
				+ EFFICIENCY_UTILIZATION
				+ EFFICIENCY_REGULATORY;
		
		MAINTAINABILITY = MAINTAINABILITY_ANALYZABILITY
				+ MAINTAINABILITY_STABILITY
				+ MAINTAINABILITY_CHANGEABILITY
				+ MAINTAINABILITY_TESTABILITY
				+ MAINTAINABILITY_REGULATORY;
		
		PORTABILITY = PORTABILITY_ADAPTABILITY
				+ PORTABILITY_INSTALLATION
				+ PORTABILITY_COEXISTENCE
				+ PORTABILITY_REPLACEABILITY
				+ PORTABILITY_REGULATORY;
	}
	
	/**
	 * 品质算法
	 * 根据系统内写死的品质系数换算品质得分
	 */
	protected void calculate() {
		GLog.logRecord(8, GStatic.gqFactor.getStrComb());
		
		FUNCTIONALITY = FUNCTIONALITY_FLEXIBILITY
				+ FUNCTIONALITY_ACCURACY
				+ FUNCTIONALITY_INTERACTIVITY
				+ FUNCTIONALITY_SECURITY
				+ FUNCTIONALITY_REGULATORY;
		double functionality = FUNCTIONALITY.doubleValue() * GStatic.gqFactor.getValue();
		FUNCTIONALITY = (int) functionality;

		RELIABILITY = RELIABILITY_MATURITY
				+ RELIABILITY_FAULTTOLERANCE
				+ RELIABILITY_RECOVERABILITY
				+ RELIABILITY_REGULATORY;
		double reliability = RELIABILITY.doubleValue() * GStatic.gqFactor.getValue();
		RELIABILITY = (int) reliability;
		
		USABILITY = USABILITY_COMPREHENSIBILITY
				+ USABILITY_EASYTOLEARN
				+ USABILITY_OPERABILITY
				+ USABILITY_STICKINESS
				+ USABILITY_REGULATORY;
		
		EFFICIENCY = EFFICIENCY_TIMING
				+ EFFICIENCY_UTILIZATION
				+ EFFICIENCY_REGULATORY;
		double efficiency = EFFICIENCY.doubleValue() * GStatic.gqFactor.getValue();
		EFFICIENCY = (int) efficiency;
		
		MAINTAINABILITY = MAINTAINABILITY_ANALYZABILITY
				+ MAINTAINABILITY_STABILITY
				+ MAINTAINABILITY_CHANGEABILITY
				+ MAINTAINABILITY_TESTABILITY
				+ MAINTAINABILITY_REGULATORY;
		double maintainability =MAINTAINABILITY.doubleValue() * GStatic.gqFactor.getValue();
		MAINTAINABILITY = (int) maintainability;
		
		PORTABILITY = PORTABILITY_ADAPTABILITY
				+ PORTABILITY_INSTALLATION
				+ PORTABILITY_COEXISTENCE
				+ PORTABILITY_REPLACEABILITY
				+ PORTABILITY_REGULATORY;
	}
}
